apiVersion: v1
kind: Service
metadata:
  name: java-application
spec:
  selector:
    app: java-application
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: login-app
spec:
  selector:
    app: login-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
